max_runtime = 60*10
LOAD_EDGES = False # if true load edges. If false compute euclidian distances.
D2T = 1 # distance to time factor
D2C = 1 # distance to cost factor
WRITE_EDGES = False # if true write all edges to excel file
WRITE_LP = False
FIX_SOLUTION = True # if we have to read solution from other instance
INIT_SOL = False # if true initialize x 
LOWER_BOUND = False # if true the lower bound procedure will be activated
VALID_INEQUALITIES = False